-- ====================================================
-- 준메디칼 MEDI-SALES 360° Supabase 4대 핵심 테이블 스키마
-- ====================================================

-- 1. 거래처 병원 마스터 테이블 (174개 병원)
CREATE TABLE IF NOT EXISTS public.hospitals (
    name TEXT PRIMARY KEY,
    region TEXT DEFAULT '세종충북',
    sales_reps JSONB DEFAULT '[]'::jsonb,
    contacts JSONB DEFAULT '[]'::jsonb,
    status TEXT DEFAULT '신규영업',
    last_activity_date TEXT,
    total_logs INTEGER DEFAULT 0,
    demo_count INTEGER DEFAULT 0,
    won_count INTEGER DEFAULT 0,
    as_count INTEGER DEFAULT 0,
    fail_count INTEGER DEFAULT 0,
    products_active JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 누적 영업활동 일지 테이블 (758건 일지)
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital TEXT NOT NULL,
    date TEXT NOT NULL,
    sales_rep TEXT NOT NULL,
    action_type TEXT DEFAULT '제품설명·소개',
    title TEXT,
    note TEXT,
    products JSONB DEFAULT '[]'::jsonb,
    product_code TEXT DEFAULT 'PROD_GENERAL',
    next_action TEXT,
    region TEXT DEFAULT '세종충북',
    contact TEXT DEFAULT '실무진',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 품목별 영업 파이프라인 테이블 (199개 딜)
CREATE TABLE IF NOT EXISTS public.pipeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital TEXT NOT NULL,
    region TEXT DEFAULT '세종충북',
    sales_rep TEXT,
    product_id TEXT NOT NULL,
    product_name TEXT NOT NULL,
    status TEXT DEFAULT '제품소개·영업중',
    last_date TEXT,
    latest_action TEXT,
    latest_note TEXT,
    demo_info JSONB,
    as_info JSONB,
    fail_reasons JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Ecount ERP 품목 마스터 테이블 (4,054개 품목)
CREATE TABLE IF NOT EXISTS public.erp_products (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    spec TEXT,
    vendor TEXT,
    category TEXT DEFAULT '일반소모품',
    keywords JSONB DEFAULT '[]'::jsonb,
    aliases JSONB DEFAULT '[]'::jsonb,
    price_in NUMERIC DEFAULT 0,
    price_out NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================
-- RLS (Row Level Security) 개방 정책 설정 (Web & Slack Bot 실시간 CRUD 허용)
-- ====================================================
ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pipeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.erp_products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public access hospitals" ON public.hospitals;
CREATE POLICY "Public access hospitals" ON public.hospitals FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access activity_logs" ON public.activity_logs;
CREATE POLICY "Public access activity_logs" ON public.activity_logs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access pipeline" ON public.pipeline;
CREATE POLICY "Public access pipeline" ON public.pipeline FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access erp_products" ON public.erp_products;
CREATE POLICY "Public access erp_products" ON public.erp_products FOR ALL USING (true) WITH CHECK (true);

-- Realtime 기능 활성화 (선택)
ALTER PUBLICATION supabase_realtime ADD TABLE public.hospitals, public.activity_logs, public.pipeline;
